# Generated by Django 5.2 on 2025-04-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_consuming', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consume',
            old_name='food',
            new_name='food_consumed',
        ),
    ]
